# Docker configuration backend
providers:
  docker:
    { }

entryPoints:
  # Redirect http to https
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

certificatesResolvers:
  lets_provider:
    acme:
      email: andrew@ealovega.dev
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: '60'
        # Required else private DNS eats the challenge
        resolvers:
          - "1.1.1.1:53"


# API and dashboard configuration
api:
  insecure: true